### PR TITLE
Add Privacy API implementation

### PR DESCRIPTION
**Pull request by tonyjbutler**
Hi David, I did this as an exercise for a job interview back in February, and it just occurred to me that it might save you a bit of work if this plugin is still being maintained. It might not be entirely complete but it should at least be a fairly decent starting point. Cheers, Tony

### CODE REVIEW

**Comment by mudrd8mz** [comment]
Wow! Many thanks Tony! I'll check the patch ASAP and will let you know.

**Comment by mudrd8mz** [comment]
I am sorry. I did not forget about this one, only did not have a chance to get to it yet.

**Comment by tonyjbutler** [comment]
No worries, it took me 6 months to create the pull request. :-)

**Comment by mudrd8mz** [comment]
Thanks again @tonyjbutler for this. I feel bad for ignoring this for so long. I just merged your pull request and I am going to release it as a new version in the plugins directory. Together with it, I've put the plugin up to adoption and marked it as seeking a new maintainer. Even this particular pull request is a clear illustration that I have not been looking after it effectively anyway. So it's fair to admit it to self and announce publicly.

**Pull request merged**
